### PR TITLE
Clean up Submission

### PR DESCRIPTION
**Pull request by akunbekov**

### CODE REVIEW

**Comment by sattvik** [comment]
Thank you.  Could you please provide your e-mail address?

We won't be covering C++ or Python, but we will do Ruby, which shares a lot of properties with each of those languages.

**Comment by sattvik** [comment]
You can just provide your e-mail in a comment here.

**Comment by akunbekov** [comment]
takunbekov@na.edu

**Comment by alikucuk** [comment]
akucuk@na.edu

**Comment by sattvik** [comment]
Thank you, I have recorded these addresses.

**Pull request closed without merging**
